# Site settings
title: Test Blog
email: ashilso29@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/testblog/" # the subpath of your site, e.g. /blog/
url: "http://jaewoooda.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  Jaewoo-Lee

# Build settings
markdown: kramdown
